### ISSUE TITLE
Unclear instructions 

### ISSUE THREAD

**Issue by TrivCodez** [LeetaoGoooo/discord-robots#1]
Many other projects have clear instructions however your doesn’t! Please make it easier for users to get their api key as there is wayyyy easier ways then this! The way you used is bullshit and is very confusing for anyone to understand.

**Comment by LeetaoGoooo** [comment]
> Many other projects have clear instructions however your doesn’t! Please make it easier for users to get their api key as there is wayyyy easier ways then this! The way you used is bullshit and is very confusing for anyone to understand.

This is my project, and I’m the one in charge. You’re just someone who wants to use it. I’m not obligated to meet your demands—it’s entirely up to me. If you don’t know how to be polite, maybe it’s time to relearn the basics.

**Comment by siyuedeqinian** [comment]
用中文怼
